#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: Service
apiVersion: v1
metadata:
  name: helidontest2
  labels:
    app: helidontest2
spec:
  type: NodePort
  selector:
    app: helidontest2
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helidontest2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helidontest2
        version: v1
    spec:
      containers:
      - name: helidontest2
        image: docker.io/amristea2/helidontest2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      - name: mysql
        image: elementalconcept/java8-mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
---
